pipeline {
  environment {
    registry = “gustavoapolinario/docker-test”
    registryCredential = ‘dockerhub’
    dockerImage = ‘’
  }
  agent any
  stages {
    stage(‘Cloning Git’) {
      steps {
        git ‘https://github.com/awssingh07/docker-jerkinspipeline.git'
      }
    }
  }
}
